kind: pod
apiVersion: v1
metadata:
  name: devboard-frontend
  namespace: devboard

spec:
  containers:
  - name: devboard-frontend
    image: vishaldocker85/devboard-frontend:latest
    ports:
      - containerPort: 4173