apiVersion: v1
kind: Pod
metadata:
  name: devboard-frontend
  namespace: devboard
spec:
  containers:
  - name: devboard-frontend
    image: trainwithshubham/devboard-frontend:latest 
    ports:
    - containerPort: 4173


