apiVersion: v1
kind: Service
metadata:
  name: devboard-postgres-service
  namespace: devboard
spec:
  selector:
    app: devboard-postgres
#  type: NodePort for BE its clusterIp by default
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: devboard-postgres  # by default clusterIp it takes
    protocol: TCP
    port: 5432  #svc port # BE clusterIp connects to the FE SVC-service that port is here. not exposed port for fronend BE port only same prot hence 8080. svc and exposed.
    targetPort: 5432  #pod ka port
  #8080 ec2 >> svc FE 30080 >> 4173 FE pod >> svc FE 30080 >> SVC BE 8080 >> deploy BE 8080 >> svc db 5432 >> deplyment container pod 5432

    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    #nodePort: 30080  # Node ka port 