apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres-deployment
  namespace: devboard
  labels:
    app:  devboard-postgres
spec:
  selector:
    matchLabels:
      app: devboard-postgres
  replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app:  devboard-postgres
    spec:
      containers:
      - name: postgres  #in postgres URl we have give postgres not devboard postgres.
        image: postgres:16-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB            # Name inside the container
            valueFrom:
              secretKeyRef:
                name: devboard-secrets                # Name of your Secret file meta
                key: POSTGRES_DB                      # Key inside the Secret

          - name: POSTGRES_PASSWORD      # Name inside the container
            valueFrom:
              secretKeyRef:
                name: devboard-secrets                # Name of your Secret file meta
                key: POSTGRES_PASSWORD                # Key inside the Secret

          - name: POSTGRES_USER          # Name inside the container 
            valueFrom:  
              configMapKeyRef:
                name: devboard-configmap              # Name of your ConfigMap file meta
                key: POSTGRES_USER                    # Key inside the ConfigMap
        readinessProbe:
          exec:
            command: ["sh", "-c", "pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)"]
          initialDelaySeconds: 15
          periodSeconds: 10
        
        volumeMounts:
          - name: init
            mountPath: /docker-entrypoint-initdb.d
            readOnly: true
      volumes:
        - name: init  #any volume name
          configMap:
            name: postgres-init   #from configmap-ini.yml meta
        
        # livenessProbe:
        #   exec:
        #     command:
        #       - /bin/sh
        #       - -c
        #       - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        
        # readinessProbe:
        #   exec:
        #     command:
        #       - /bin/sh
        #       - -c
        #       - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 5
        #   failureThreshold: 3