apiVersion: v1
kind: Secret
metadata:
  name: devboard-secrets
  namespace: devboard
type: Opaque
data:
  POSTGRES_PASSWORD:  ZGV2Ym9hcmQ=
  POSTGRES_DB:  ZGV2Ym9hcmQ= # this decodes to devboard   user i will add in configmap
  
  
  # NOTE: All values must be base64-encoded
  # add your secrets here as key-value pairs, e.g.
  #username: {{ .Values.username | b64enc }}    #Check Your Values File: Look in your Helm chart for the values.yaml file. Your real username and password are saved in plain text under keys like username and 
