# Goal - I have to do SAST for my Code

name: Code Quality

on:
    workflow_call:  # you can call this workflow before/after any other workflow

jobs:
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
            
            - name: Setup NodeJs
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json
            
            - name: Install npm Packages
              run: npm ci
              working-directory: frontend

            - name: Run Linter  #Unused variables, Undefined variables, Code style violations React-specific rules (if eslint-plugin-react is configured) Import/export issues


              run: npm run lint
              working-directory: frontend

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                go-version: '1.23'
                go-version-file: 'go.mod'
                cache-dependency-path: go.sum
            
            - name: Run Go Formatter  # formatting and import ordering
              run: go fmt ./...
              working-directory: backend

            - name: Run Go Vet  # suspicious code constructs (e.g. wrong format strings)
              run: go vet ./...
              working-directory: backend