# this will scans the secrets using git leaks

name: Secret scanning
on:
  workflow_call:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Code leaks check
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.