# this scans the SAST static code using sonar qube which has set op rules for all codes. like a cheting of notebook rules.
name: Sonar SAST scan
on:
    workflow_call:
jobs:
    sonar-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v6
              with:
                # Disabling shallow clones is recommended for improving the relevancy of reporting
                fetch-depth: 0    
            - name: check connectivity
              run: | 
                echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL || env.SONAR_HOST_URL || '' }}" curl -v --max-time 10 "${{ secrets.SONAR_HOST_URL }}" || true curl -v --max-time 10 "${{ secrets.SONAR_HOST_URL }}/api/v2/analysis/version" || true
              
            #- name: SonarQube Scan
             # uses: SonarSource/sonarqube-scan-action@v8.2.0 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
            #  env:
             #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
             #   with:
        # This tells ngrok to bypass the browser warning page
             #   args: >
                #    -Dsonar.ws.additionalHeaders="ngrok-skip-browser-warning:true"
            - name: Run Sonar Scanner
              run: |
                  # Update system repositories and install unzip/wget utilities
                    sudo apt update && sudo apt install -y unzip wget
                    
                    # Download the SonarScanner CLI binary package
                    wget https://sonarsource.com
                    
                    # Extract the downloaded archive package
                    unzip sonar-scanner-cli-5.0.1.3006-linux.zip
                    
                    # Relocate the scanner directory to global /opt partition
                    sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
                    
                    # Append the directory path to system user environment configurations
                    echo 'export PATH="$PATH:/opt/sonar-scanner/bin"' >> ~/.bashrc
                    
                    # Clean up leftover installer zip archive
                    rm sonar-scanner-cli-5.0.1.3006-linux.zip
                    
                    # Refresh active shell interface variables
                    source ~/.bashrc
                    
                    # Test binary installation version status
                    sonar-scanner -v
                    
                    sonar-scanner \
                      -Dsonar.projectKey=nodejs-go-postgres-devboard \
                      -Dsonar.projectName=nodejs-go-postgres-devboard \
                      -Dsonar.sources=backend,frontend \
                      -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                      -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
                      -Dsonar.ws.additionalHeaders="ngrok-skip-browser-warning:true"
