# this files will do the complete CI production ready security scanning for this project
name: DevSecOps
on:
    #push:
     #   branches:
     #       - main
     workflow_dispatch:
jobs:
    code-linting-nodejs-go:
        uses: ./.github/workflows/1-code-lint.yml
    code-scan-gitleaks-nodejs-go:
        uses: ./.github/workflows/2-secret-scan.yml
    dependency-check-nodejs-go:
        uses: ./.github/workflows/3-dependency.yml
    docker-linting-build-trivy-checks:
        uses: ./.github/workflows/4-docker-checks.yml
        secrets: inherit
    sonar-qube-checks:
        uses: ./.github/workflows/5-sonar-qube.yml
        secrets: inherit
    code-test-checks:
        uses: ./.github/workflows/6-code-test.yml   
    dockerHub-image-push:
        uses: ./.github/workflows/7-docker-push.yml
        secrets: inherit
    docker-deploy:
        needs: [code-linting-nodejs-go, code-scan-gitleaks-nodejs-go, dependency-check-nodejs-go, docker-linting-build-trivy-checks, sonar-qube-checks, code-test-checks, dockerHub-image-push]
        uses: ./.github/workflows/8-deploy.yml
        secrets: inherit
    
    dast-scan-OWASP-zap:
        needs: [docker-deploy]
        uses: ./.github/workflows/9-dast-scan.yml
        secrets: inherit
