# this files will do the complete CI production ready security scanning for this project
name: DevSecOps
on:
    push:
        branches:
            - main
jobs:
    code-linting:
        uses: ./.github/workflows/1-code-lint.yml
    code-scan-gitleaks:
        uses: ./.github/workflows/2-secret-scan.yml