# Goal - to check whether the application code coverage doesn't have security threats/issues

name: Sonar Qube Scan

on:
    workflow_call:

jobs:
    sonar-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v8.2.0
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}